name: Deploy dongtai website v2

on:
  release:
    types: [created]
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: hugo
        uses: klakegg/actions-hugo@1.0.0

      - name: Setup upterm session
        uses: lhotari/action-upterm@v1

      - name: Setup Ossutil
        uses: manyuanrong/setup-ossutil@v2.0
        with:
          endpoint: ${{ secrets.DONGTAI_OSS_ENDPOINT }}
          access-key-id: ${{ secrets.DONGTAI_OSS_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.DONGTAI_OSS_ACCESS_KEY_SECRET }}

      # - name: Upload images to oss
      #   run: |
      #     ossutil cp -f /tmp/dongtai-mysql-${{ steps.release.outputs.version }}.tar.gz oss://huoqi-public/iast/server-package/${{ steps.release.outputs.version }}/
      #     ossutil cp -f /tmp/dongtai-redis-${{ steps.release.outputs.version }}.tar.gz oss://huoqi-public/iast/server-package/${{ steps.release.outputs.version }}/
